/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import glbank.Card;
import glbank.database.ConnectionProvider;

/**
 *
 * @author Martin
 */
public class EditCardDialog extends javax.swing.JDialog {

    private Card card;

    /**
     * Creates new form EditCardDialog
     */
    public EditCardDialog(java.awt.Frame parent, boolean modal, Card card) {
        super(parent, modal);
        initComponents();
        this.card = card;
        initForm();
    }

    private void initForm() {
        lblInvalidPin.setVisible(false);
        if (card.isBlocked()) {
            btnBlockUnblock.setText("Unblock");
        } else {
            btnBlockUnblock.setText("Block");
        }
        txtEditPin.setText("" + card.getPincode());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEditPin = new javax.swing.JTextField();
        btnBlockUnblock = new javax.swing.JButton();
        btnConfirmEditCard = new javax.swing.JButton();
        btnCancelEditCard = new javax.swing.JButton();
        lblInvalidPin = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Edit bank card");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Pin :");

        btnBlockUnblock.setText("Block");
        btnBlockUnblock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlockUnblockActionPerformed(evt);
            }
        });

        btnConfirmEditCard.setText("Confirm");
        btnConfirmEditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditCardActionPerformed(evt);
            }
        });

        btnCancelEditCard.setText("Cancel");
        btnCancelEditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditCardActionPerformed(evt);
            }
        });

        lblInvalidPin.setForeground(new java.awt.Color(204, 0, 51));
        lblInvalidPin.setText("Invalid pin!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelEditCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmEditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBlockUnblock)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInvalidPin)
                            .addComponent(txtEditPin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEditPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInvalidPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBlockUnblock)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmEditCard)
                    .addComponent(btnCancelEditCard))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelEditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditCardActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelEditCardActionPerformed

    private void btnBlockUnblockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlockUnblockActionPerformed
        if (card.isBlocked()) {
            card.setBlocked(false);
            btnBlockUnblock.setText("Block");
        } else {
            card.setBlocked(true);
            btnBlockUnblock.setText("Unblock");
        }
    }//GEN-LAST:event_btnBlockUnblockActionPerformed

    private void btnConfirmEditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditCardActionPerformed
        String pin = txtEditPin.getText();
        if(pin.trim().length() == 4){
            lblInvalidPin.setVisible(false);
            card.setPincode(Integer.parseInt(pin));
            new ConnectionProvider().updateClientCard(card);
            this.dispose();
        }
        else{
            lblInvalidPin.setVisible(true);
        }
    }//GEN-LAST:event_btnConfirmEditCardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlockUnblock;
    private javax.swing.JButton btnCancelEditCard;
    private javax.swing.JButton btnConfirmEditCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblInvalidPin;
    private javax.swing.JTextField txtEditPin;
    // End of variables declaration//GEN-END:variables
}
