/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import glbank.Client;
import glbank.database.ConnectionProvider;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Martin
 */
public class NewClientDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewClientDialog
     */
    public NewClientDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblClientPasswordError.setVisible(false);
        lblEmptyFieldsError.setVisible(false);
        lblInvalidClientLogin.setVisible(false);
    }

    private boolean validateForm() {
        if (isClientCityValid() && isClientDobValid() && isClientFirstNameValid()
                && isClientLastNameValid() && isClientHouseNumberValid()
                && isClientPostCodeValid() && isClientStreetValid()
                && isClientPasswordValid() && isLoginUnique()) {
            lblClientPasswordError.setVisible(false);
            lblEmptyFieldsError.setVisible(false);
            lblInvalidClientLogin.setVisible(false);
            return true;
        } else {
            if (!isClientPasswordValid()) {
                lblClientPasswordError.setVisible(true);
            } else {
                lblClientPasswordError.setVisible(false);
            }

            if (!(isClientCityValid() && isClientDobValid() && isClientFirstNameValid()
                    && isClientLastNameValid() && isClientHouseNumberValid()
                    && isClientPostCodeValid() && isClientStreetValid())) {
                lblEmptyFieldsError.setVisible(true);
            } else {
                lblEmptyFieldsError.setVisible(false);
            }

            if (!isLoginUnique()) {
                lblInvalidClientLogin.setVisible(true);
            } else {
                lblInvalidClientLogin.setVisible(false);
            }
        }
        return false;
    }

    private boolean isClientCityValid() {
        return !"".equals(txtClientCity.getText().trim());
    }

    private boolean isClientDobValid() {
        return clientDob.getDate() != null;
    }

    private boolean isClientFirstNameValid() {
        return !"".equals(txtClientFirstName.getText().trim());
    }

    private boolean isClientLastNameValid() {
        return !"".equals(txtClientLastName.getText().trim());
    }

    private boolean isClientHouseNumberValid() {
        return !"".equals(txtClientHouseNumber.getText().trim());
    }

    private boolean isClientPostCodeValid() {
        return !"".equals(txtClientPostCode.getText().trim());
    }

    private boolean isClientStreetValid() {
        return !"".equals(txtClientStreet.getText().trim());
    }

    private boolean isClientPasswordValid() {
        return new ChangePasswordDialog().isNewPasswordValid(
                txtClientPassword.getText());
    }

    private boolean isLoginUnique() {
        ConnectionProvider conn = new ConnectionProvider();
        List<String> allLogins = conn.getClientLogins();
        String enteredLogin = txtClientLogin.getText();
        for (String login : allLogins) {
            if (login.equals(enteredLogin)) {
                return false;
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtClientFirstName = new javax.swing.JTextField();
        txtClientLastName = new javax.swing.JTextField();
        txtClientStreet = new javax.swing.JTextField();
        txtClientHouseNumber = new javax.swing.JTextField();
        txtClientPostCode = new javax.swing.JTextField();
        txtClientCity = new javax.swing.JTextField();
        txtClientEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtClientLogin = new javax.swing.JTextField();
        txtClientPassword = new javax.swing.JTextField();
        btnSumbitNewClient = new javax.swing.JButton();
        btnCancelNewClient = new javax.swing.JButton();
        lblEmptyFieldsError = new javax.swing.JLabel();
        lblInvalidClientLogin = new javax.swing.JLabel();
        lblClientPasswordError = new javax.swing.JLabel();
        clientDob = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("New client");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Street :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Birth Date :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("House Number :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("City :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Postal code :");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Email :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Login :");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Password :");

        btnSumbitNewClient.setBackground(new java.awt.Color(153, 153, 153));
        btnSumbitNewClient.setForeground(new java.awt.Color(0, 0, 0));
        btnSumbitNewClient.setText("Submit");
        btnSumbitNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumbitNewClientActionPerformed(evt);
            }
        });

        btnCancelNewClient.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelNewClient.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelNewClient.setText("Cancel");
        btnCancelNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewClientActionPerformed(evt);
            }
        });

        lblEmptyFieldsError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmptyFieldsError.setForeground(new java.awt.Color(255, 51, 51));
        lblEmptyFieldsError.setText("* Please enter all fields!");

        lblInvalidClientLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblInvalidClientLogin.setForeground(new java.awt.Color(255, 51, 51));
        lblInvalidClientLogin.setText("* Not unique login!");

        lblClientPasswordError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblClientPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        lblClientPasswordError.setText("* Invalid password!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtClientLastName)
                                .addComponent(txtClientStreet)
                                .addComponent(txtClientCity)
                                .addComponent(txtClientEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtClientHouseNumber)
                                .addComponent(txtClientPostCode, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                            .addComponent(clientDob, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSumbitNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClientPasswordError)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtClientLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtClientPassword))
                                    .addComponent(lblInvalidClientLogin)))
                            .addComponent(lblEmptyFieldsError)))
                    .addComponent(txtClientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(381, 381, 381))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtClientLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInvalidClientLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClientPasswordError))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtClientHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtClientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblEmptyFieldsError)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSumbitNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumbitNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumbitNewClientActionPerformed
        if (validateForm()) {
            String lastName = txtClientLastName.getText();
            String firstName = txtClientFirstName.getText();
            String email = txtClientEmail.getText();
            String street = txtClientStreet.getText();
            String numStr = txtClientHouseNumber.getText();
            if (numStr.equals("")) {
                numStr = "0";
            }
            int houseNumber;
            boolean isNumeric = numStr.chars().allMatch(Character::isDigit);
            if (isNumeric) {
                houseNumber = Integer.parseInt(txtClientHouseNumber.getText());
            } else {
                houseNumber = 0;
            }
            String postCode = txtClientPostCode.getText();
            String userName = txtClientLogin.getText();
            
            //casting util date to sql date
            Date dob = clientDob.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String stringDate = dateFormat.format(dob);
            java.sql.Date sqlDob = java.sql.Date.valueOf(stringDate);
            
            String city = txtClientCity.getText();
            String password = txtClientPassword.getText();
            
            Client client = new Client(0, lastName, firstName, email, street,
                    houseNumber, postCode, userName, false, false, sqlDob, city);
            
            new ConnectionProvider().addClientIntoDatabase(client, password);
            new MainForm(); 
            this.dispose();                 
        }
    }//GEN-LAST:event_btnSumbitNewClientActionPerformed

    private void btnCancelNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewClientActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelNewClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelNewClient;
    private javax.swing.JButton btnSumbitNewClient;
    private org.jdesktop.swingx.JXDatePicker clientDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblClientPasswordError;
    private javax.swing.JLabel lblEmptyFieldsError;
    private javax.swing.JLabel lblInvalidClientLogin;
    private javax.swing.JTextField txtClientCity;
    private javax.swing.JTextField txtClientEmail;
    private javax.swing.JTextField txtClientFirstName;
    private javax.swing.JTextField txtClientHouseNumber;
    private javax.swing.JTextField txtClientLastName;
    private javax.swing.JTextField txtClientLogin;
    private javax.swing.JTextField txtClientPassword;
    private javax.swing.JTextField txtClientPostCode;
    private javax.swing.JTextField txtClientStreet;
    // End of variables declaration//GEN-END:variables
}
