/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.panels;

import glbank.Account;
import glbank.database.ConnectionProvider;
import gui.NewAccountDialog;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JFrame;

/**
 *
 * @author Martin
 */
public class ClientAccountsPanel extends javax.swing.JPanel {

    private int idc;
    private int idemp;
    private float value;
    private int selectedAccountIndex;
    private List<Account> accountsList;

    /**
     * Creates new form ClientAccountPanel
     */
    public ClientAccountsPanel(int idc, int idemp) {
        initComponents();
        this.idc = idc;
        this.idemp = idemp;
        showListOfAccounts();
        lblBalanceValue.setText("");
        selectedAccountIndex = comboBoxAccountId.getSelectedIndex();
        showAccountBalance(selectedAccountIndex);
    }

    private void showListOfAccounts() {
        comboBoxAccountId.removeAllItems();
        accountsList = new ConnectionProvider().getClientAccounts(idc);
        if (accountsList != null) {
            for (Account account : accountsList) {
                comboBoxAccountId.addItem("" + account.getIdacc());
            }
            if (comboBoxAccountId.getItemCount() != 0) {
                comboBoxAccountId.setSelectedIndex(selectedAccountIndex);
            }
        }
    }

    private void showAccountBalance(int selectedAccount) {
        if (selectedAccount >= 0) {
            lblBalanceValue.setText("" + accountsList.get(selectedAccount).getBalance());
        }
    }

    private void updateBalance(int mark) {
        if (comboBoxAccountId.getItemCount() != 0 && !"".equals(txtAdditionalValue.getText())) {
            try {
                value = mark * Float.parseFloat(txtAdditionalValue.getText());
            } catch (Exception ex) {
                value = 0;
            }
            value = (float) Math.round(value * 100) / 100;
            if ((mark == -1 && accountsList.get(selectedAccountIndex).getBalance() > Math.abs(value))
                    || mark == 1) {
                long selectedAccountId = accountsList.get(selectedAccountIndex).getIdacc();
                
                //updating in database
                new ConnectionProvider().addCashToClient(selectedAccountId, idemp, value);
                showListOfAccounts();
                showAccountBalance(selectedAccountIndex);
            }
        }
    }

    private long generateRandomAccountNumber() {
        boolean isUnique = false;
        long randomAccNum;

        do {
            randomAccNum = ThreadLocalRandom.current().nextLong(100000000, 900000000) * 11;
            for (long accountNumber : new ConnectionProvider().getAllAccountNumbers()) {
                if (randomAccNum == accountNumber) {
                    isUnique = false;
                    break;
                }
                isUnique = true;
            }
        } while (isUnique == false);

        return randomAccNum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxAccountId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblBalanceValue = new javax.swing.JLabel();
        txtAdditionalValue = new javax.swing.JTextField();
        btnSubMoney = new javax.swing.JButton();
        btnAddMoney = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAddNewAccount = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Account id :");

        comboBoxAccountId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAccountIdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Balance :");

        lblBalanceValue.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblBalanceValue.setText("value");

        btnSubMoney.setText("Sub -");
        btnSubMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMoneyActionPerformed(evt);
            }
        });

        btnAddMoney.setText("Add +");
        btnAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoneyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Cash transaction");

        btnAddNewAccount.setText("Add new account");
        btnAddNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBalanceValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSubMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnAddMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAdditionalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(139, 139, 139))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboBoxAccountId, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(156, 156, 156))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxAccountId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblBalanceValue)
                    .addComponent(txtAdditionalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubMoney)
                    .addComponent(btnAddMoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNewAccount)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxAccountIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAccountIdActionPerformed
        selectedAccountIndex = comboBoxAccountId.getSelectedIndex();
        showAccountBalance(selectedAccountIndex);
    }//GEN-LAST:event_comboBoxAccountIdActionPerformed

    private void btnSubMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMoneyActionPerformed
        updateBalance(-1);
    }//GEN-LAST:event_btnSubMoneyActionPerformed

    private void btnAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoneyActionPerformed
        updateBalance(1);
    }//GEN-LAST:event_btnAddMoneyActionPerformed

    private void btnAddNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewAccountActionPerformed
        long randomAccNum = generateRandomAccountNumber();
        if (new ConnectionProvider().addNewAccount(idc, randomAccNum)) {
            showListOfAccounts();
            showAccountBalance(selectedAccountIndex);
            NewAccountDialog newAccDialog = new NewAccountDialog((JFrame) this.getRootPane().getParent(), true, randomAccNum);
            newAccDialog.setLocationRelativeTo(null);
            newAccDialog.setVisible(true);

        }
    }//GEN-LAST:event_btnAddNewAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoney;
    private javax.swing.JButton btnAddNewAccount;
    private javax.swing.JButton btnSubMoney;
    private javax.swing.JComboBox<String> comboBoxAccountId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBalanceValue;
    private javax.swing.JTextField txtAdditionalValue;
    // End of variables declaration//GEN-END:variables
}
